config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :games
    root 'static_pages#home'
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/about'
    get 'static_pages/contact'
    get 'static_pages/grid'
    get 'sessions/new'
    get 'users/new'
    #root  'welcome#index'
    #get 'welcome/index'
    get  '/signup',  to: 'users#new'
    
    resources :articles do
      resources :comments
    end

    resources :users

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def grid
  	@grid_demo = GridDemo.new
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Hi this is my Rails App I created so you can play my Battleships Go! game online</p>

<p>Big up to Michael Hartl for his <A target="_blank" href="https://www.railstutorial.org/book/">tutorial</A> from which I got most of the code for this site.</p>

<p>Internationalization tuturial care of the team at 

<%= link_to "lokalise", "https://blog.lokalise.com/rails-i18n/", target: "_blank", rel: "nofollow" %> and the <%= link_to "RailsGuide - Rails Internationalization (I18n) API", "https://guides.rubyonrails.org/i18n.html", target: "_blank", rel: "nofollow" %></p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Neil about the Battleships Go! game at rogerne@btinternet.com.
</p>

app/views/static_pages/grid.html.erb
<% provide(:title, "Grid Demo") %>

<h1>A Test Grid created on the fly</h1>

<p>Test Grid</p>


  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
    	<div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

	<% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
	
	<% end %>

	<% GridDemo.new.grid_container.each do |x, y|  %>
  	<% if y == "X" %>
  		  <div class="<%= x %>"><%= y %></div>  
      <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div>  
	  <% end %>
	<%end %> 
  
  </div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1><%= t 'global.game.name' %></h1>

<h2><%= t 'static_pages.home.head_2' %></h2>

<div class="gameswrapper">
  <div class="gamesheader"><%= t 'static_pages.home.table_avail_games' %></div>
  <div class="gamesheader"><%= t 'static_pages.home.table_details' %></div>
  <div class="gamesheader"><%= t 'static_pages.home.table_launch_games' %></div>

  <div class="gamesbox">
    <%= image_tag "battle.jpg" %>
  </div>
  <div class="gamesbox">
  	<%= t 'static_pages.home.battleships_details' %>
  </div>
  <div class="gamesbox">
  	<%= link_to t('static_pages.home.btn_play'), games_path, class: "btn btn-sm btn-primary" %>
  </div>
</div>

<h2></h2>
<%= link_to t('static_pages.home.btn_sign_up_now'), signup_path, class: "btn btn-lg btn-primary" %>
</div>