config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :games
    root 'static_pages#home'
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/about'
    get 'static_pages/contact'
    get 'static_pages/grid'
    get 'sessions/new'
    get 'users/new'
    #root  'welcome#index'
    #get 'welcome/index'
    get  '/signup',  to: 'users#new'
    
    resources :articles do
      resources :comments
    end

    resources :users

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  
  has_many :comments, dependent: :destroy

	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]


	 def index
    @articles = Article.all
  end

	def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

	def create
	 #render plain: params[:article].inspect
	 #@article = Article.new(params[:article])
   #@article = Article.new(params.require(:article).permit(:title, :text))
   @article = Article.new(article_params)

    if @article.save
      redirect_to @article
     else
      render 'new'
    end
	end
  
  def update
  @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end

      def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
      <%= link_to "Create new Article", new_article_path %>
    <p>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
     
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>
</table>
 

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<!-- <h2>Comments</h2> -->
Comments
<%= render @article.comments %>

<!-- <h2>Add a comment:</h2> -->
<p>
	Add a new Comment
<%= render 'comments/form' %>