config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :games
    root 'static_pages#home'
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/about'
    get 'static_pages/contact'
    get 'static_pages/grid'
    get 'sessions/new'
    get 'users/new'
    #root  'welcome#index'
    #get 'welcome/index'
    get  '/signup',  to: 'users#new'
    
    resources :articles do
      resources :comments
    end

    resources :users

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new 
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  	 @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
    else
      flash[:success] = "Oops!"
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

    <%= form_for(@user) do |f| %>
   

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <p>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <p>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <p>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

<% if logged_in? %>
   <%= link_to "Log out", logout_path, method: :delete %>
 <% else %>
   <%= link_to "Log in", login_path %><p>
   <%= link_to "Sign up now!", signup_path %>
<% end %>
<%= debug(params) if Rails.env.development? %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div>
  <div>
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'  %>
		<p>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'  %>
		<p>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'  %>
		<p>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control'  %>
		<p>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>
<p>
<%= debug(params) if Rails.env.development? %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>