config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :games
    root 'static_pages#home'
    get 'static_pages/home'
    get 'static_pages/help'
    get 'static_pages/about'
    get 'static_pages/contact'
    get 'static_pages/grid'
    get 'sessions/new'
    get 'users/new'
    #root  'welcome#index'
    #get 'welcome/index'
    get  '/signup',  to: 'users#new'
    
    resources :articles do
      resources :comments
    end

    resources :users

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t('global.footer.blurb') %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('global.footer.about'), static_pages_about_path %></li>
      <li><%= link_to t('global.footer.contact'), static_pages_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <div class="container">
    <nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
     <!-- Brand -->
      <a class="navbar-brand" href="#"><%= link_to t('global.game.name'), root_path, id: "logo" %>
      </a>
  
      <ul class="navbar-nav">

        <li class="nav-item active"><%= link_to t('global.header.home'), root_path, :class => "nav-link" %></li>
        <li class="nav-item active"><%= link_to t('global.header.articles'), articles_path, :class => "nav-link" %></li>        
        <li class="nav-item active"><%= link_to t('global.header.help'), static_pages_help_path, :class => "nav-link" %></li>
        <!-- Dropdown -->
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            <%= t 'global.header.language' %>
          </a>
          <div class="dropdown-menu">
            <%= link_to 'English', url_for(locale: :en), :class => "dropdown-item" %>
            <%= link_to 'ไทย', url_for(locale: :th), :class => "dropdown-item" %>  
            <%= link_to 'हिन्दी भाषा', url_for(locale: :hi), :class => "dropdown-item" %>                
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item active"><%= link_to t('global.header.log_out'), logout_path, method: :delete, :class => "nav-link" %></li>
          <li class="nav-item active"><%= link_to t('global.header.settings'), edit_user_path(current_user), :class => "nav-link" %></li>
        <% else %>
          <li class="nav-item active"><%= link_to t('global.header.log_in'), login_path, :class => "nav-link" %></li>
        <% end %>
      </ul>
    </nav>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= render 'layouts/shim' %>
  </head>
  <body onLoad="setInit()">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>